### ISSUE TITLE
ndarray-show should be dependency instead of devDependency

### ISSUE THREAD

**Issue by jalava** [scijs/ndarray-tests#3]
as show is called from actual code and not tests of ndarray-tests, ndarray-show should be included in dependencies, not devDependencies.

**Comment by rreusser** [comment]
Ahhhh. I keep mixing that up and fail to correct it. Sorry about that! Let me see what I can do from my phone…

**Comment by rreusser** [comment]
Okay, so I fixed it and tagged a new version 1.2.2. Unfortunately, I'm doing this from my phone since I'm without computer for the next week and a half so I can't currently `npm publish`.  Solutions: 
- `npm install -g ndarray-show` so that it finds the dependency
- switch package to the github repo instead of npm
- either existing collaborator (or you if you want me to add you so that you can publish) can git clone + npm publish. I think that's really all there is to it.

Also some API naming weirdness (verbs? No verbs?) that I'd like to clean up, so if you run into anything weird, just file a bug or submit a pull request and I'll do what I can from my phone!

**Comment by rreusser** [comment]
Note: it's not even used in the code; I just neglected to remove it after requiring it while debugging since npm install -g tends to mask these things, I think.

**Comment by Planeshifter** [comment]
Just published it, `npm install ndarray-tests` will now install the most recent version.
